# Reproduces the comparison between cell-center patching and subcell clipping.
# Generated by ChatGPT.
import numpy as np
import pandas as pd

def rect_vertices(center, size, angle_rad):
    cx, cz = center
    lx, lz = size
    hx, hz = lx / 2.0, lz / 2.0
    local = np.array([[-hx, -hz], [hx, -hz], [hx, hz], [-hx, hz]])
    c, s = np.cos(angle_rad), np.sin(angle_rad)
    R = np.array([[c, -s], [s, c]])
    return local @ R.T + np.array([cx, cz])

def point_in_rotated_rect(points, center, size, angle_rad):
    cx, cz = center
    lx, lz = size
    c, s = np.cos(angle_rad), np.sin(angle_rad)
    Rt = np.array([[c, s], [-s, c]])
    local = (points - np.array([cx, cz])) @ Rt.T
    return (np.abs(local[:, 0]) <= lx / 2.0) & (np.abs(local[:, 1]) <= lz / 2.0)

def cross2(a, b):
    return a[0] * b[1] - a[1] * b[0]

def line_intersection_with_clip_edge(p1, p2, a, b, eps=1e-14):
    r = p2 - p1
    s = b - a
    denom = cross2(r, s)
    if abs(denom) < eps:
        return p2.copy()
    t = cross2(a - p1, s) / denom
    return p1 + t * r

def clip_polygon_against_edge(poly, a, b, eps=1e-12):
    if len(poly) == 0:
        return poly
    output = []
    prev = poly[-1]
    prev_inside = cross2(b - a, prev - a) >= -eps
    for curr in poly:
        curr_inside = cross2(b - a, curr - a) >= -eps
        if curr_inside:
            if not prev_inside:
                output.append(line_intersection_with_clip_edge(prev, curr, a, b))
            output.append(curr)
        elif prev_inside:
            output.append(line_intersection_with_clip_edge(prev, curr, a, b))
        prev = curr
        prev_inside = curr_inside
    return np.array(output, dtype=float)

def clip_square_by_convex_polygon(square_poly, clip_poly):
    poly = square_poly.copy()
    for i in range(len(clip_poly)):
        a = clip_poly[i]
        b = clip_poly[(i + 1) % len(clip_poly)]
        poly = clip_polygon_against_edge(poly, a, b)
        if len(poly) == 0:
            break
    return poly

def polygon_area_centroid(poly):
    if len(poly) < 3:
        return 0.0, np.array([np.nan, np.nan])
    x = poly[:, 0]
    y = poly[:, 1]
    xp = np.roll(x, -1)
    yp = np.roll(y, -1)
    cross = x * yp - xp * y
    A = 0.5 * np.sum(cross)
    if abs(A) < 1e-14:
        return 0.0, np.array([np.nan, np.nan])
    Cx = np.sum((x + xp) * cross) / (6.0 * A)
    Cy = np.sum((y + yp) * cross) / (6.0 * A)
    return abs(A), np.array([Cx, Cy])

def make_grid(xmin, xmax, zmin, zmax, Nx, Nz):
    x_edges = np.linspace(xmin, xmax, Nx + 1)
    z_edges = np.linspace(zmin, zmax, Nz + 1)
    dx = x_edges[1] - x_edges[0]
    dz = z_edges[1] - z_edges[0]
    return x_edges, z_edges, dx, dz

def cell_center_patch_metrics(x_edges, z_edges, center, size, angle_rad, p_star):
    x_centers = 0.5 * (x_edges[:-1] + x_edges[1:])
    z_centers = 0.5 * (z_edges[:-1] + z_edges[1:])
    dx = x_edges[1] - x_edges[0]
    dz = z_edges[1] - z_edges[0]
    cell_area = dx * dz
    Xc, Zc = np.meshgrid(x_centers, z_centers, indexing="ij")
    pts = np.column_stack([Xc.ravel(), Zc.ravel()])
    inside = point_in_rotated_rect(pts, center, size, angle_rad).reshape(len(x_centers), len(z_centers)).astype(float)
    area = inside.sum() * cell_area
    xbar = (Xc * inside).sum() * cell_area / area
    zbar = (Zc * inside).sum() * cell_area / area
    return {"area": area, "xbar": xbar, "zbar": zbar, "Fy": p_star * area, "Mz": p_star * area * xbar}

def clipped_patch_metrics(x_edges, z_edges, rect_poly, p_star):
    area_sum = 0.0
    first_moment_x = 0.0
    first_moment_z = 0.0
    for i in range(len(x_edges) - 1):
        for j in range(len(z_edges) - 1):
            square = np.array([
                [x_edges[i],     z_edges[j]],
                [x_edges[i + 1], z_edges[j]],
                [x_edges[i + 1], z_edges[j + 1]],
                [x_edges[i],     z_edges[j + 1]],
            ], dtype=float)
            clipped = clip_square_by_convex_polygon(square, rect_poly)
            A, C = polygon_area_centroid(clipped)
            area_sum += A
            if A > 0:
                first_moment_x += A * C[0]
                first_moment_z += A * C[1]
    xbar = first_moment_x / area_sum
    zbar = first_moment_z / area_sum
    return {"area": area_sum, "xbar": xbar, "zbar": zbar, "Fy": p_star * area_sum, "Mz": p_star * area_sum * xbar}

if __name__ == "__main__":
    kA, kB, delta = 30.0, 90.0, 0.10
    p_star = (kA * kB / (kA + kB)) * delta
    center = (0.22, -0.10)
    size = (1.20, 0.55)
    angle_rad = np.deg2rad(28.0)
    rect_poly = rect_vertices(center, size, angle_rad)
    xmin, xmax = -0.70, 1.20
    zmin, zmax = -0.75, 0.55
    for N in [18, 36, 72]:
        x_edges, z_edges, *_ = make_grid(xmin, xmax, zmin, zmax, N, N)
        cc = cell_center_patch_metrics(x_edges, z_edges, center, size, angle_rad, p_star)
        cl = clipped_patch_metrics(x_edges, z_edges, rect_poly, p_star)
        print(f"N={N}")
        print("  cell-center   ", cc)
        print("  subcell-clip  ", cl)
